use super::entities::{ToolArgSpec, ToolEntry};

pub const RISK_LANE_HELP: &str =
    "Accepted lanes: tiny, normal, high-risk. Use tiny instead of low.";

pub const RESPONSIBILITIES: &[&str] = &[
    "Task specification",
    "Context selection",
    "Tool access",
    "Project memory",
    "Task state",
    "Observability",
    "Failure attribution",
    "Verification",
    "Permissions",
    "Entropy auditing",
    "Intervention recording",
];

pub fn compiled_tool_registry() -> Vec<ToolEntry> {
    vec![
        tool(
            "harness-cli",
            "init",
            "init",
            "Create the harness database.",
            &[],
            "Task state",
            "0.1.0",
        ),
        tool(
            "harness-cli",
            "migrate",
            "migrate",
            "Apply pending schema migrations.",
            &[],
            "Task state",
            "0.1.0",
        ),
        tool(
            "harness-cli",
            "import brownfield",
            "import brownfield",
            "Seed durable records from markdown state.",
            &[],
            "Project memory",
            "0.1.0",
        ),
        tool(
            "harness-cli",
            "intake",
            "intake",
            "Record a feature intake classification.",
            &[
                ("type", "string", true),
                ("summary", "string", true),
                ("lane", "enum", true),
            ],
            "Task specification",
            "0.1.0",
        ),
        tool(
            "harness-cli",
            "story add",
            "story add",
            "Create a durable story record.",
            &[
                ("id", "string", true),
                ("title", "string", true),
                ("lane", "enum", true),
            ],
            "Task state",
            "0.1.0",
        ),
        tool(
            "harness-cli",
            "story update",
            "story update",
            "Update story status, proof flags, or verification command.",
            &[("id", "string", true)],
            "Task state",
            "0.1.0",
        ),
        tool(
            "harness-cli",
            "story verify",
            "story verify",
            "Run one story verify_command and record pass or fail.",
            &[("id", "string", true)],
            "Verification",
            "0.1.6",
        ),
        tool(
            "harness-cli",
            "story verify-all",
            "story verify-all",
            "Run every configured story verification command.",
            &[],
            "Verification",
            "0.1.8",
        ),
        tool(
            "harness-cli",
            "decision add",
            "decision add",
            "Create a durable decision record.",
            &[("id", "string", true), ("title", "string", true)],
            "Project memory",
            "0.1.0",
        ),
        tool(
            "harness-cli",
            "decision verify",
            "decision verify",
            "Run one decision verification command.",
            &[("id", "string", true)],
            "Verification",
            "0.1.6",
        ),
        tool(
            "harness-cli",
            "backlog add",
            "backlog add",
            "Record a harness improvement proposal.",
            &[("title", "string", true)],
            "Entropy auditing",
            "0.1.0",
        ),
        tool(
            "harness-cli",
            "backlog close",
            "backlog close",
            "Close a backlog item with outcome evidence.",
            &[("id", "integer", true)],
            "Entropy auditing",
            "0.1.0",
        ),
        tool(
            "harness-cli",
            "trace",
            "trace",
            "Record an agent execution trace.",
            &[("summary", "string", true)],
            "Observability",
            "0.1.0",
        ),
        tool(
            "harness-cli",
            "score-trace",
            "score-trace",
            "Score trace detail against lane requirements.",
            &[("id", "integer", false)],
            "Observability",
            "0.1.4",
        ),
        tool(
            "harness-cli",
            "score-context",
            "score-context",
            "Score trace context reads against context rules.",
            &[("trace-id", "integer", true)],
            "Context selection",
            "0.1.8",
        ),
        tool(
            "harness-cli",
            "audit",
            "audit",
            "Run drift checks and compute entropy score.",
            &[],
            "Entropy auditing",
            "0.1.8",
        ),
        tool(
            "harness-cli",
            "propose",
            "propose",
            "Generate harness improvement proposals from observed patterns.",
            &[("commit", "flag", false)],
            "Entropy auditing",
            "0.1.8",
        ),
        tool(
            "harness-cli",
            "query matrix",
            "query matrix",
            "Show durable story proof matrix.",
            &[],
            "Task state",
            "0.1.0",
        ),
        tool(
            "harness-cli",
            "query backlog",
            "query backlog",
            "Show harness improvement backlog.",
            &[],
            "Entropy auditing",
            "0.1.0",
        ),
        tool(
            "harness-cli",
            "query decisions",
            "query decisions",
            "Show durable decision records.",
            &[],
            "Project memory",
            "0.1.0",
        ),
        tool(
            "harness-cli",
            "query intakes",
            "query intakes",
            "Show recent intake records.",
            &[],
            "Task specification",
            "0.1.0",
        ),
        tool(
            "harness-cli",
            "query traces",
            "query traces",
            "Show recent trace records.",
            &[],
            "Observability",
            "0.1.0",
        ),
        tool(
            "harness-cli",
            "query friction",
            "query friction",
            "Show traces that recorded harness friction.",
            &[],
            "Failure attribution",
            "0.1.4",
        ),
        tool(
            "harness-cli",
            "query interventions",
            "query interventions",
            "Show human or review intervention records.",
            &[],
            "Intervention recording",
            "0.1.8",
        ),
        tool(
            "harness-cli",
            "query stats",
            "query stats",
            "Show durable record counts.",
            &[],
            "Task state",
            "0.1.0",
        ),
        tool(
            "harness-cli",
            "query tools",
            "query tools",
            "Show compiled and registered tool manifest entries.",
            &[],
            "Tool access",
            "0.1.8",
        ),
        tool(
            "harness-cli",
            "query sql",
            "query sql",
            "Run arbitrary SQL against harness.db.",
            &[("query", "string", true)],
            "Tool access",
            "0.1.0",
        ),
        tool(
            "harness-cli",
            "tool register",
            "tool register",
            "Register an external project tool.",
            &[("name", "string", true), ("command", "string", true)],
            "Tool access",
            "0.1.8",
        ),
        tool(
            "harness-cli",
            "tool remove",
            "tool remove",
            "Remove a registered external tool.",
            &[("name", "string", true)],
            "Tool access",
            "0.1.8",
        ),
        tool(
            "harness-cli",
            "intervention add",
            "intervention add",
            "Record a human or review intervention.",
            &[
                ("type", "enum", true),
                ("description", "string", true),
                ("source", "enum", true),
            ],
            "Intervention recording",
            "0.1.8",
        ),
    ]
}

fn tool(
    provider: &str,
    name: &str,
    command: &str,
    description: &str,
    args: &[(&str, &str, bool)],
    responsibility: &str,
    since: &str,
) -> ToolEntry {
    ToolEntry {
        provider: provider.to_owned(),
        name: name.to_owned(),
        command: command.to_owned(),
        description: description.to_owned(),
        args: args
            .iter()
            .map(|(name, arg_type, required)| ToolArgSpec {
                name: (*name).to_owned(),
                arg_type: (*arg_type).to_owned(),
                required: *required,
                help: None,
            })
            .collect(),
        responsibility: responsibility.to_owned(),
        source: "compiled".to_owned(),
        since: since.to_owned(),
    }
}
